export const LAYOUT_TYPES = {
  ONE_COL_TWO_CELLS: 'ONE_COL_TWO_CELLS',
  TWO_CELLS_ONE_COL: 'TWO_CELLS_ONE_COL',
  TWO_ROWS: 'TWO_ROWS',
  TWO_COLS: 'TWO_COLS',
  ONE_ROW_TWO_CELLS: 'ONE_ROW_TWO_CELLS',
  TWO_CELLS_ONE_ROW: 'TWO_CELLS_ONE_ROW',
  FOUR_CELLS: 'FOUR_CELLS',
}
