/* eslint-disable react-hooks/rules-of-hooks */
import { useSelector } from "react-redux";

import Head from "next/head";

import { selectBackgroundImage, selectCurrentTheme } from "@/store/slices/appStatusSlice";

import { THEME_KEYS } from "@/constants/constants";

const withAppLayout = WrappedComponent => {
  function WithAppLayout(props) {
    const gBackgroundImage = useSelector(selectBackgroundImage);
    const gTheme = useSelector(selectCurrentTheme);

    return (
      <>
        <Head>
          <title>Interactive Console 2</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div
          className={
            "w-full max-w-[1180px] max-h-[820px] h-[820px] portrait:max-w-[100vw] portrait:max-h-[69.492vw] portrait:h-[69.492vw] m-auto relative " +
            (gTheme == THEME_KEYS.SOPHISTICATED ? "bg-black" : "bg-gray")
          }
          style={{
            backgroundImage: `${gBackgroundImage ? `url(${gBackgroundImage})` : ""}`,
            backgroundSize: "cover",
            backgroundRepeat: "no-repeat",
          }}
        >
          <WrappedComponent {...props} />
        </div>
      </>
    );
  }

  return WithAppLayout;
};

export default withAppLayout;
